apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: mlflow
        image: docker.io/larmoreg/mlflow
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: NAMESPACE_HEADER
          value: $(MF_NAMESPACE_HEADER)
        - name: USERID_HEADER
          value: $(MF_USERID_HEADER)
      serviceAccountName: mlflow
