apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow
  name: mlflow-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlflow
  sessionAffinity: None
  type: ClusterIP
